### ISSUE TITLE
Remove cycle from linked list

### ISSUE THREAD

**Issue by kunalkabra46** [kapilkumar2001/Data-Structures-and-Algorithms#6]
hey @kapilkumar2001  i want to contribute through this issue...

please allow me and add hactoberfest and hacktoberfest accepted label to it...

**Comment by kapilkumar2001** [comment]
Hi @kunalkabra46 you can create a PR with your changes.

**Comment by ShaluMishra13** [comment]
hii, please assign this to me i can do it very well . I am a java coder

**Comment by kapilkumar2001** [comment]
Hi @ShaluMishra13 .. You can create PR with your changes.

**Comment by kapilkumar2001** [comment]
Hi @tusharnain4578 you can write code for any other problem and make PR.

**Comment by tusharnain4578** [comment]
> Hi @tusharnain4578 you can write code for any other problem and make PR.

Ok, I am coding Merge Sort for Linked Lists and making PR.
